export interface Settings {
  displayBorderRect: {
    left: number;
    top: number;
    width: number;
    height: number;
  };
  displayFontName: string;
  displayFontSize: number;
  displayFontAlign: "left" | "center" | "right";
  displayFontBold: boolean;
  displayFontItalic: boolean;
  displayFontUnderline: boolean;
  displayTextShadowOffset: number;
  backgroundColor: string;
  textColor: string;
  textBorderColor: string;
  textBorderWidth: number;
  message: string;
  useNonSplittingWords: boolean;
  realSectionPreview: boolean;
  previewFontInSections: boolean;
  nonSplittingWordList: string[];
  hideChordsInReadonlyEditor: boolean;
  sectionHighlightInEditor: boolean;
  sectionSelByEditorLineSel: boolean;
  sectionSelByEditorDblclk: boolean;
  keepAwake: boolean;
  pictureFolder: string;
  selectedBackgroundImageId: string | null;
  backgroundImageFit: "touchInner" | "touchOuter" | "stretch" | "touchInnerMargins" | "touchOuterMargins" | "stretchMargins";
  useTextSimilarities: boolean;
  searchMaxResults: number;
  traditionalSearchCaseSensitive: boolean;
  traditionalSearchWholeWords: boolean;
  useFontAwesomeIcons: boolean;
  baseFontSize: number;
  fontSizeMode: "manual" | "auto-resolution" | "auto-resolution-dpi";

  iWebEnabled: boolean;
  webServerPort: number;
  webServerPath: string;
  webServerDomainName: string;
  externalWebDisplayEnabled: boolean;
  registerLocalServer: boolean;
  longPollTimeout: number;
  netDisplayJpegQuality: number;
  netDisplayImageScale: number;
  useSectionColoring: boolean;
  verseSectionColor: string;
  chorusSectionColor: string;
  bridgeSectionColor: string;
  checkSectionsProjectable: boolean;
  contentBasedSections: boolean;
  displayFaultThreshold: number;
  displayCroppedTextBgColor: string;
  displayAllowFontSizeReduction: boolean;
  displayMinimumFontSize: number;
  displayMinimumFontSizePercent: number;
  displayShowFontSizeReduction: "NONE" | "SECTIONS" | "PLAYLIST" | "BOTH";
  displayShrinkedTextBgColor: string;
  displayPlaylistUpdateInterval: number;
  printingBB: boolean;
  printingMetaData: boolean;
  printingSuperScript: boolean;
  printingTitle: boolean;
  printingMollMode: string;
  printingSectionLabels: "None" | "Abbreviated" | "Full";
  allClientsCanUseLeaderMode: boolean;
  selectedLeader?: string;
  leaderModeClients: string[];
  minWebRenderSize: {
    width: number;
    height: number;
  };
  defaultChordSystem: "G" | "S";
  displayMonitorId: string;
  lastSyncDate?: string;
  syncDeclineTimeoutMinutes: number;
  serverPeekIntervalMinutes: number;
  logLevel: number;
  logAutoExpandParams: boolean;
  theme: "light" | "dark" | "auto";
  language: "en" | "hu" | "auto";
  showPreferredOnly: boolean;
  qrCodeInPreview: boolean;
  qrCodeX: number;
  qrCodeY: number;
  qrCodeSizePercent: number;
  showTextInPreview: boolean;
  showImageInPreview: boolean;
}
